#!/usr/bin/env python3
"""CLAIMS REGISTER — a DONE must name a check that passed.

OS-COMPLIANCE.md asserted 43 rows as DONE in prose, bound to nothing. Several of
them were false at the moment of writing: "Phase 3 complete, 21 agent files" was
true about the files and false about the system, because not one of them resolved.

So: a claim may say DONE only if it names a check id that PASSED in the last run.
Everything else is UNVERIFIED — which is not an accusation, it is the absence of a
machine that could tell. Generates docs/company/CHECKS.md.

The headline drops from 43 to whatever is actually bound. That drop is the
deliverable. If the number does not fall, nothing is bound.
"""
import json
import os
import re
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
COMPANY = os.path.join(ROOT, "docs", "company")


def main():
    try:
        st = json.load(open(os.path.join(ROOT, "dashboard", "status.json")))
    except Exception:
        print("no status.json — run status_report.py first", file=sys.stderr)
        return 1

    res = st.get("results", [])
    passing = [r for r in res if r.get("ok") and r.get("n", 0) > 0]
    skipped = [r for r in res if r.get("skipped")]
    failing = [r for r in res if not r.get("ok") and not r.get("skipped")]

    md = ""
    p = os.path.join(COMPANY, "OS-COMPLIANCE.md")
    if os.path.exists(p):
        md = open(p).read()
    done_rows = [l for l in md.split("\n")
                 if l.strip().startswith("|") and re.search(r"\bDONE\b", l)]

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    out = [
        "<!-- GENERATED by scripts/company/claims_register.py. Do not edit. -->",
        "",
        "# CHECKS — what the company can actually prove",
        "",
        f"Generated {stamp} from `dashboard/status.json`.",
        "",
        "**The rule: a row in `OS-COMPLIANCE.md` may say DONE only if it names a check id below "
        "that passed in the last run.** Anything else is `UNVERIFIED` — not an accusation, just "
        "the absence of a machine that could tell.",
        "",
        f"| claims asserted DONE in prose | {len(done_rows)} |",
        "|---|---|",
        f"| **checks passing, so bindable** | **{len(passing)}** |",
        f"| checks not runnable here | {len(skipped)} |",
        f"| checks failing | {len(failing)} |",
        "",
        "The gap between those first two numbers is the honest state of this company's "
        "self-knowledge. It closes by writing checks, never by editing the table.",
        "",
        "## Bindable now",
        "",
        "| check id | n | what it proves |",
        "|---|---|---|",
    ]
    for r in sorted(passing, key=lambda x: x["id"]):
        out.append(f"| `{r['id']}` | {r.get('n')} | {str(r.get('detail',''))[:88]} |")

    if skipped:
        out += ["", "## Not runnable in this context", "",
                "Reported apart from a pass on purpose: an unrunnable check and a passing check are "
                "different facts, and collapsing them is how a report goes green on a system nobody "
                "checked.", "", "| check id | why |", "|---|---|"]
        for r in sorted(skipped, key=lambda x: x["id"]):
            out.append(f"| `{r['id']}` | {str(r.get('detail',''))[:88]} |")

    if failing:
        out += ["", "## Failing", "", "| check id | detail | fix |", "|---|---|---|"]
        for r in sorted(failing, key=lambda x: x["id"]):
            out.append(f"| `{r['id']}` | {str(r.get('detail',''))[:64]} | {str(r.get('fix') or '')[:56]} |")

    out += [
        "",
        "## What is NOT bindable, and never will be",
        "",
        "Some rows in `OS-COMPLIANCE.md` record history rather than state — *\"the CEO overturned a "
        "finding that did not survive verification\"* is true, and there is no check that can hold it "
        "true tomorrow. Those stay `UNVERIFIED` permanently, and that is correct. A register that "
        "found a way to mark them green would be worth nothing.",
        "",
        "Others are not obtainable at all: `MAPE` needs a ground-truth sold price, and `DATA.md` "
        "established this architecture has none. Reporting it would be inventing it.",
    ]

    with open(os.path.join(COMPANY, "CHECKS.md"), "w") as fh:
        fh.write("\n".join(out) + "\n")

    print(f"  claims asserted DONE: {len(done_rows)}")
    print(f"  bindable today:       {len(passing)}")
    print(f"  wrote docs/company/CHECKS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
